name: Crate Versions Check

on:
  pull_request_target:
    types: [labeled, opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  check-crates:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'ci:check release') || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Publishing dry run
        uses: katyo/publish-crates@v2
        with:
          dry-run: true
          # check-repo: false
